import { Header } from "@/components/Header";
import { ArrowLeft, Calculator, Check, Phone } from "@/components/Icons";
import { ProductShowcase } from "@/components/ProductShowcase";
import { sitePath } from "@/lib/paths";
import { catalog, refractorySizes } from "@/lib/catalog";
import { catalogHref } from "@/lib/products";

const cats = [
  {name:"آجر نما",count:"۱۶ مدل",description:"نسوز، قزاقی، دکوراتیو، رستیک، لعابی، سنتی و رسی",image:"/images/generated/category-firebrick.png",filter:"facade"},
  {name:"آجر کوره",count:"۴ مدل",description:"آجرهای صنعتی مقاوم در برابر حرارت بالا",image:"/images/products/pa-f02.webp",filter:"kiln"},
  {name:"آجر کف",count:"۳ مدل",description:"کف‌فرش مقاوم برای حیاط و فضای معماری",image:"/images/generated/category-floor.png",filter:"floor"},
  {name:"آجر معمولی",count:"۶ مدل",description:"لفتون، فشاری و سفال برای دیوارچینی و سازه",image:"/images/products/pa-w01.webp",filter:"ordinary"},
  {name:"مصالح جانبی",count:"۵ مدل",description:"بندکشی، چسب، نانو، شوینده و اسپیسر",image:"/images/products/pa-r02.webp",filter:"accessories"}
];

export default function Home() {
  return <main>
    <Header/>
    <section className="hero">
      <div className="container heroGrid">
        <div className="heroContent"><span className="eyebrow">خرید مستقیم از کارخانه</span><h1>نمای ماندگار،<br/><em>با انتخاب دقیق آجر.</em></h1><p>مجموعه تخصصی آجر نما برای معماران، سازندگان و پروژه‌های شاخص؛ با مشاوره انتخاب، محاسبه تعداد و ارسال سراسری.</p><div className="heroCtas"><a className="btn btnPrimary" href="#quote">دریافت قیمت پروژه <ArrowLeft/></a><a className="btn btnSecondary" href="#products">مشاهده محصولات</a></div><div className="heroTrust"><span><Check/> تضمین کیفیت</span><span><Check/> نمونه واقعی</span><span><Check/> ارسال سراسری</span></div></div>
        <div className="heroVisual"><div className="heroPanel"><img className="heroScene" src={sitePath("/images/generated/hero-brick-villa.png")} alt="ویلای معاصر با نمای آجر نسوز جهان‌نما"/><img className="heroLogo" src={sitePath("/images/logo-symbol-dark.png")} alt="نشان آجر جهان‌نما" width="112" height="112"/><div className="floatingCard"><small>محصول منتخب معماران</small><strong>آجر نسوز قرمز رستیک</strong><span>بافت طبیعی • مقاوم در برابر یخبندان</span></div></div><div className="heroStat"><strong>+۱۸</strong><span>سال تجربه در تولید آجر نما</span></div></div>
      </div>
    </section>

    <section className="stats"><div className="container statsGrid"><div><strong>۴۵۰+</strong><span>پروژه اجراشده</span></div><div><strong>۳۶</strong><span>مدل و رنگ تخصصی</span></div><div><strong>۲۴</strong><span>استان تحت پوشش</span></div><div><strong>۹۲٪</strong><span>رضایت مشتریان</span></div></div></section>

    <section className="section" id="products"><div className="container"><div className="sectionHead"><div><span className="eyebrow">انتخاب براساس کاربرد</span><h2>دسته‌بندی محصولات</h2></div><a className="textLink" href="#store-products">مشاهده همه محصولات <ArrowLeft/></a></div><div className="categoryGrid referenceCategories">{cats.map((c,i)=><a className={`categoryCard cat${i+1}`} href={`#cat-${catalog[i].slug}`} key={c.name}><span className="categoryIndex">۰{i+1}</span><img className="categoryImage" src={c.image} alt={c.name} loading="lazy"/><span className="categoryCount">{c.count}</span><h3>{c.name}</h3><p>{c.description}</p><b>مشاهده محصولات <ArrowLeft/></b></a>)}</div></div></section>

    <section className="section catalogSection" id="catalog"><div className="container"><div className="sectionHead"><div><span className="eyebrow">فهرست کامل فروشگاه</span><h2>همه دسته‌ها، دقیق و مرتب</h2></div><p className="sectionNote">برای دریافت موجودی و قیمت روز با دفتر فروش تماس بگیرید.</p></div><div className="catalogGrid">{catalog.map((group,index)=><article className="catalogGroup" id={`cat-${group.slug}`} key={group.slug}><span className="catalogNumber">۰{index+1}</span><h3>{group.name}</h3>{group.children?.map(child=><div className="catalogChild" id={`cat-${child.slug}`} key={child.slug}><strong><a href={catalogHref(child.slug)}>{child.name}</a></strong>{child.children?.length ? <div className="catalogTags">{child.children.map(item=><a id={`cat-${item.slug}`} href={catalogHref(item.slug)} key={item.slug}>{item.name}</a>)}</div>:null}{child.slug === "refractory-brick" && <div className="sizeBlock"><small>ابعاد آجر نسوز</small><div>{refractorySizes.map(size=><span key={size}>{size}</span>)}</div></div>}</div>)}</article>)}</div></div></section>

    <ProductShowcase/>

    <section className="section" id="calculator"><div className="container calculatorWrap"><div className="calcContent"><span className="eyebrow light">محاسبه‌گر هوشمند</span><h2>تعداد آجر پروژه‌تان را در کمتر از یک دقیقه محاسبه کنید.</h2><p>متراژ، ابعاد آجر و درصد پرت را وارد کنید؛ تعداد تقریبی قالب و بسته موردنیاز را دریافت کنید.</p><ul><li><Check/> محاسبه بر اساس بندکشی استاندارد</li><li><Check/> لحاظ‌کردن پرت پروژه</li><li><Check/> تبدیل مستقیم نتیجه به پیش‌فاکتور</li></ul></div><div className="calcCard"><Calculator/><h3>محاسبه سریع</h3><label>متراژ نما (مترمربع)<input defaultValue="120" inputMode="decimal"/></label><label>نوع آجر<select defaultValue="ap33"><option value="ap33">نسوز AP33 - ۷×۳۲</option><option>سفید صدفی - ۵.۵×۲۶</option></select></label><label>درصد پرت<input defaultValue="7" inputMode="numeric"/></label><div className="calcResult"><span>تعداد تقریبی</span><strong>۵,۱۳۶ قالب</strong></div><button className="btn btnPrimary">دریافت پیش‌فاکتور محاسبه‌شده</button></div></div></section>

    <section className="section" id="projects"><div className="container"><div className="sectionHead"><div><span className="eyebrow">پروژه‌های اجراشده</span><h2>آجر جهان‌نما در معماری واقعی</h2></div><a className="textLink" href="#">همه پروژه‌ها <ArrowLeft/></a></div><div className="projectsGrid"><article className="project projectLarge"><img src={sitePath("/images/generated/project-white-gray.png")} alt="ویلای مدرن با آجر سفید و طوسی در لواسان" loading="lazy"/><div className="projectOverlay"><span>ویلای مدرن • لواسان</span><h3>ترکیب آجر سفید و طوسی</h3><a href="#">مشاهده پروژه <ArrowLeft/></a></div></article><article className="project projectSmall p2"><img src={sitePath("/images/generated/project-red.png")} alt="ساختمان مسکونی با نمای آجر نسوز رستیک در تهران" loading="lazy"/><div className="projectOverlay"><span>مسکونی • تهران</span><h3>نمای نسوز رستیک</h3></div></article><article className="project projectSmall p3"><img src={sitePath("/images/generated/project-qazaqi.png")} alt="بازسازی حیاط ایرانی با آجر قزاقی در اصفهان" loading="lazy"/><div className="projectOverlay"><span>بازسازی • اصفهان</span><h3>آجر قزاقی سنتی</h3></div></article></div></div></section>

    <section className="section quoteSection" id="quote"><div className="container quoteGrid"><div><span className="eyebrow">مشاوره و استعلام</span><h2>برای پروژه شما، دقیق‌ترین پیشنهاد را آماده می‌کنیم.</h2><p>اطلاعات اولیه را ثبت کنید؛ کارشناس فروش در ساعات کاری با شما تماس می‌گیرد.</p><div className="contactCard"><Phone/><div><small>تماس مستقیم با فروش</small><a href="tel:+989133678359"><strong>۰۹۱۳۳۶۷۸۳۵۹</strong></a><a href="tel:+989132333527">۰۹۱۳۲۳۳۳۵۲۷</a></div></div><div className="salesOffice"><span>دفتر فروش آجر آذرشین</span><p>اصفهان، شهرک صنعتی دولت‌آباد، نبش خیابان استاد همایی ۲۲</p><small>کدپستی: ۸۳۴۱۶۵۷۲۰۰</small><a className="mapLink" href="https://nshn.ir/rboeaQYx0d3N" target="_blank" rel="noopener noreferrer">مسیریابی روی نشان <ArrowLeft/></a></div></div><form className="quoteForm"><div className="fieldRow"><label>نام و نام خانوادگی<input placeholder="مثلاً محمد رضایی"/></label><label>شماره موبایل<input placeholder="۰۹۱۲۱۲۳۴۵۶۷" inputMode="tel"/></label></div><div className="fieldRow"><label>شهر پروژه<input placeholder="مثلاً تهران"/></label><label>متراژ تقریبی<input placeholder="مثلاً ۱۲۰ متر"/></label></div><label>محصول موردنظر<select><option>انتخاب کنید</option>{cats.map(c=><option key={c.name}>{c.name}</option>)}</select></label><button className="btn btnPrimary" type="button">ثبت درخواست مشاوره</button><small>با ثبت فرم، با شرایط حفظ حریم خصوصی موافقت می‌کنید.</small></form></div></section>

    <footer className="footer" id="contact"><div className="container footerGrid"><div className="footerBrand"><img src={sitePath("/images/logo-dark.png")} alt="لوگوی کامل آجر جهان‌نما" width="189" height="142" loading="lazy"/><p>تولید و عرضه مستقیم آجر نما برای پروژه‌های معماری و ساختمانی در سراسر ایران.</p><strong className="officeName">دفتر فروش آجر آذرشین</strong></div><div><h4>محصولات</h4>{cats.slice(0,4).map(c=><a href="#" key={c.name}>{c.name}</a>)}</div><div><h4>نشانی دفتر فروش</h4><p>اصفهان، شهرک صنعتی دولت‌آباد، نبش خیابان استاد همایی ۲۲</p><p>کدپستی: ۸۳۴۱۶۵۷۲۰۰</p><a href="https://nshn.ir/rboeaQYx0d3N" target="_blank" rel="noopener noreferrer">مشاهده روی نقشه نشان</a></div><div><h4>ارتباط با ما</h4><p>شنبه تا پنجشنبه، ۸ تا ۱۸</p><a href="tel:+989133678359">۰۹۱۳۳۶۷۸۳۵۹</a><a href="tel:+989132333527">۰۹۱۳۲۳۳۳۵۲۷</a></div></div><div className="container footerBottom"><span>© ۱۴۰۵ آجر جهان‌نما</span><span>طراحی‌شده برای تجربه خرید حرفه‌ای</span></div></footer>
    <a className="whatsapp" href="https://wa.me/989133678359" target="_blank" rel="noopener noreferrer" aria-label="مشاوره واتساپی با آجر جهان‌نما">WA</a>
  </main>;
}
